### PR TITLE
Change for security concern

### PR DESCRIPTION
**Pull request by YYTVicky**

### CODE REVIEW

**Comment by rombert** [comment]
Thanks for the PR @YYTVicky . Can you please file a Sling jira issue where you explain the need for this change? You should probably also CC @stefan-egli there.

**Comment by Mahir92** [comment]
Hi @rombert, an [issue ](https://issues.apache.org/jira/browse/SLING-9418)has been created in Sling JIRA, addressing the issue that @YYTVicky raised.

**Comment by rombert** [comment]
Thanks. I'll defer to @stefan-egli on this one, as he has worked on this module the most

**Comment by Mahir92** [comment]
Hi @rombert , if there is any update from you or @stefan-egli regarding the proposed fix then please let me know. It will be very appreciated.

Thank you.

**Comment by Mahir92** [comment]
Hi @rombert , if there is any update from you or @stefan-egli regarding the proposed fix, please let me know. It would be helpful in understanding if it's a correct suggestion to give.

Thank you.

**Comment by rombert** [comment]
@Mahir92 - I will defer to Stefan, I am not sure of all the implications of this PR.

**Comment by stefan-egli** [comment]
@YYTVicky @Mahir92 , thx for the PR, I'll follow up. One note that would be good to have adjusted in the PR: we normally like to have the commit message start with the JIRA ticket, so instead of `Change for security concern` it would be `SLING-9418: Change for security concern`

**Comment by stefan-egli** [comment]
Rejected as per [this comment](https://issues.apache.org/jira/browse/SLING-9418?focusedCommentId=17101654&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17101654). Thx for the PR anyway!

**Comment by Mahir92** [comment]
Hello @stefan-egli , thanks a lot for taking time to get back to us. If I have any better suggestion to provide I will reopen the issue, I hope that's okay.

**Comment by stefan-egli** [comment]
@Mahir92, sure, feel free to do so.

**Pull request closed without merging**
